const mockedJob = {
  candidates: [
    {
      personId: 2456,
      fullName: "VeliaHaddox",
      appliedDate: "Aug 9, 2020 2:00:00 AM",
      status: "Start Manual Onboarding",
      jobId: 0,
    },
    {
      personId: 2457,
      fullName: "VeliaHaddox",
      appliedDate: "Aug 9, 2020 2:00:00 AM",
      status: "Approved",
      jobId: 0,
    },
    {
      personId: 4316,
      fullName: "ChrissyDarrah",
      appliedDate: "Aug 9, 2020 2:00:00 AM",
      status: "Start Manual Onboarding",
      jobId: 0,
    },
    {
      personId: 4317,
      fullName: "ChrissyDarrah",
      appliedDate: "Aug 9, 2020 2:00:00 AM",
      status: "Interviewed",
      jobId: 0,
    },
    {
      personId: 4318,
      fullName: "ChrissyDarrah",
      appliedDate: "Aug 9, 2020 2:00:00 AM",
      status: "Approved",
      jobId: 0,
    },
    {
      personId: 1900,
      fullName: "WinterLovin",
      appliedDate: "Aug 9, 2020 2:00:00 AM",
      status: "Start Manual Onboarding",
      jobId: 0,
    },
    {
      personId: 1901,
      fullName: "WinterLovin",
      appliedDate: "Aug 9, 2020 2:00:00 AM",
      status: "Interviewed",
      jobId: 0,
    },
    {
      personId: 1902,
      fullName: "WinterLovin",
      appliedDate: "Aug 9, 2020 2:00:00 AM",
      status: "Rejected",
      jobId: 0,
    },
    {
      personId: 1112,
      fullName: "YasminFranzone",
      appliedDate: "Aug 9, 2020 2:00:00 AM",
      status: "Start Manual Onboarding",
      jobId: 0,
    },
    {
      personId: 1113,
      fullName: "YasminFranzone",
      appliedDate: "Aug 9, 2020 2:00:00 AM",
      status: "Interviewed",
      jobId: 0,
    },
    {
      personId: 1114,
      fullName: "YasminFranzone",
      appliedDate: "Aug 9, 2020 2:00:00 AM",
      status: "Approved",
      jobId: 0,
    },
  ],
  id: 103,
  number: "2020-4444",
  title: "Full Time Marketing Coordinator",
  openPositions: 1,
  jobType: "Exempt",
  createdDate: "Aug 9, 2020 2:00:00 AM",
  lastUpdated: "Aug 9, 2020 2:00:00 AM",
  externalId: "05",
  folder: "job template",
  street: "Street 12345",
  street2: "Suite 102",
  city: "Stockton",
  zip: "99099",
  state: "California",
  country: "United States",
};

export default mockedJob;
