const mockedJobs = [
  {
    jobId: 1,
    jobTitle: "Mining & Quarrying of Nonmetallic Minerals (No Fuels)",
    createdDate: "3/24/2020",
    folder: "Home",
    state: false,
  },
  {
    jobId: 2,
    jobTitle: "Savings Institutions",
    createdDate: "7/7/2020",
    folder: "Computers",
    state: true,
  },
  {
    jobId: 3,
    jobTitle: "n/a",
    createdDate: "7/18/2020",
    folder: "Grocery",
    state: false,
  },
  {
    jobId: 4,
    jobTitle: "n/a",
    createdDate: "9/18/2019",
    folder: "Grocery",
    state: true,
  },
  {
    jobId: 5,
    jobTitle: "Clothing/Shoe/Accessory Stores",
    createdDate: "3/9/2020",
    folder: "Automotive",
    state: true,
  },
  {
    jobId: 6,
    jobTitle: "Major Pharmaceuticals",
    createdDate: "10/26/2019",
    folder: "Computers",
    state: false,
  },
  {
    jobId: 7,
    jobTitle: "Major Pharmaceuticals",
    createdDate: "9/27/2019",
    folder: "Beauty",
    state: true,
  },
  {
    jobId: 8,
    jobTitle: "Industrial Machinery/Components",
    createdDate: "10/20/2019",
    folder: "Grocery",
    state: false,
  },
  {
    jobId: 9,
    jobTitle: "Major Pharmaceuticals",
    createdDate: "6/12/2020",
    folder: "Movies",
    state: false,
  },
  {
    jobId: 10,
    jobTitle: "Major Banks",
    createdDate: "2/25/2020",
    folder: "Grocery",
    state: true,
  },
  {
    jobId: 11,
    jobTitle: "n/a",
    createdDate: "6/22/2020",
    folder: "Shoes",
    state: true,
  },
  {
    jobId: 12,
    jobTitle: "Industrial Specialties",
    createdDate: "6/28/2020",
    folder: "Movies",
    state: false,
  },
  {
    jobId: 13,
    jobTitle: "Electric Utilities: Central",
    createdDate: "12/22/2019",
    folder: "Garden",
    state: true,
  },
  {
    jobId: 14,
    jobTitle: "n/a",
    createdDate: "9/12/2019",
    folder: "Baby",
    state: true,
  },
  {
    jobId: 15,
    jobTitle: "Oil Refining/Marketing",
    createdDate: "11/2/2019",
    folder: "Games",
    state: true,
  },
  {
    jobId: 16,
    jobTitle: "Major Pharmaceuticals",
    createdDate: "10/19/2019",
    folder: "Movies",
    state: true,
  },
  {
    jobId: 17,
    jobTitle: "Major Chemicals",
    createdDate: "4/19/2020",
    folder: "Games",
    state: true,
  },
  {
    jobId: 18,
    jobTitle: "Real Estate Investment Trusts",
    createdDate: "6/1/2020",
    folder: "Baby",
    state: true,
  },
  {
    jobId: 19,
    jobTitle: "Specialty Insurers",
    createdDate: "2/23/2020",
    folder: "Baby",
    state: true,
  },
  {
    jobId: 20,
    jobTitle: "Restaurants",
    createdDate: "8/20/2019",
    folder: "Industrial",
    state: true,
  },
  {
    jobId: 21,
    jobTitle: "Pollution Control Equipment",
    createdDate: "8/4/2020",
    folder: "Outdoors",
    state: true,
  },
  {
    jobId: 22,
    jobTitle: "Business Services",
    createdDate: "10/22/2019",
    folder: "Kids",
    state: true,
  },
  {
    jobId: 23,
    jobTitle: "n/a",
    createdDate: "6/7/2020",
    folder: "Shoes",
    state: true,
  },
  {
    jobId: 24,
    jobTitle: "Industrial Machinery/Components",
    createdDate: "9/9/2019",
    folder: "Jewelery",
    state: true,
  },
  {
    jobId: 25,
    jobTitle: "Major Pharmaceuticals",
    createdDate: "12/2/2019",
    folder: "Books",
    state: true,
  },
  {
    jobId: 26,
    jobTitle: "n/a",
    createdDate: "11/15/2019",
    folder: "Health",
    state: true,
  },
  {
    jobId: 27,
    jobTitle: "Integrated oil Companies",
    createdDate: "12/21/2019",
    folder: "Health",
    state: true,
  },
  {
    jobId: 28,
    jobTitle: "n/a",
    createdDate: "4/8/2020",
    folder: "Grocery",
    state: true,
  },
  {
    jobId: 29,
    jobTitle: "n/a",
    createdDate: "9/13/2019",
    folder: "Baby",
    state: false,
  },
  {
    jobId: 30,
    jobTitle: "Major Pharmaceuticals",
    createdDate: "1/3/2020",
    folder: "Movies",
    state: true,
  },
  {
    jobId: 31,
    jobTitle: "Marine Transportation",
    createdDate: "4/14/2020",
    folder: "Garden",
    state: false,
  },
  {
    jobId: 32,
    jobTitle: "Food Distributors",
    createdDate: "4/20/2020",
    folder: "Outdoors",
    state: false,
  },
  {
    jobId: 33,
    jobTitle: "Business Services",
    createdDate: "6/29/2020",
    folder: "Beauty",
    state: true,
  },
  {
    jobId: 34,
    jobTitle: "Major Banks",
    createdDate: "9/17/2019",
    folder: "Beauty",
    state: false,
  },
  {
    jobId: 35,
    jobTitle: "Industrial Machinery/Components",
    createdDate: "8/12/2019",
    folder: "Shoes",
    state: false,
  },
  {
    jobId: 36,
    jobTitle: "Oil & Gas Production",
    createdDate: "4/19/2020",
    folder: "Shoes",
    state: false,
  },
  {
    jobId: 37,
    jobTitle: "Real Estate Investment Trusts",
    createdDate: "6/29/2020",
    folder: "Tools",
    state: true,
  },
  {
    jobId: 38,
    jobTitle: "Semiconductors",
    createdDate: "5/10/2020",
    folder: "Computers",
    state: false,
  },
  {
    jobId: 39,
    jobTitle: "Property-Casualty Insurers",
    createdDate: "10/13/2019",
    folder: "Industrial",
    state: false,
  },
  {
    jobId: 40,
    jobTitle: "n/a",
    createdDate: "6/29/2020",
    folder: "Tools",
    state: false,
  },
  {
    jobId: 41,
    jobTitle: "Biotechnology: Biological Products (No Diagnostic Substances)",
    createdDate: "11/8/2019",
    folder: "Computers",
    state: true,
  },
  {
    jobId: 42,
    jobTitle: "Paper",
    createdDate: "5/5/2020",
    folder: "Beauty",
    state: true,
  },
  {
    jobId: 43,
    jobTitle: "Business Services",
    createdDate: "3/23/2020",
    folder: "Movies",
    state: false,
  },
  {
    jobId: 44,
    jobTitle: "n/a",
    createdDate: "6/20/2020",
    folder: "Beauty",
    state: false,
  },
  {
    jobId: 45,
    jobTitle: "Real Estate Investment Trusts",
    createdDate: "7/19/2020",
    folder: "Beauty",
    state: true,
  },
  {
    jobId: 46,
    jobTitle: "EDP Services",
    createdDate: "6/12/2020",
    folder: "Grocery",
    state: true,
  },
  {
    jobId: 47,
    jobTitle: "Other Consumer Services",
    createdDate: "2/11/2020",
    folder: "Toys",
    state: false,
  },
  {
    jobId: 48,
    jobTitle: "Marine Transportation",
    createdDate: "12/24/2019",
    folder: "Health",
    state: false,
  },
  {
    jobId: 49,
    jobTitle: "n/a",
    createdDate: "8/1/2020",
    folder: "Home",
    state: false,
  },
  {
    jobId: 50,
    jobTitle: "n/a",
    createdDate: "4/27/2020",
    folder: "Sports",
    state: true,
  },
  {
    jobId: 51,
    jobTitle: "Telecommunications Equipment",
    createdDate: "3/28/2020",
    folder: "Kids",
    state: true,
  },
  {
    jobId: 52,
    jobTitle: "Savings Institutions",
    createdDate: "7/15/2020",
    folder: "Clothing",
    state: true,
  },
  {
    jobId: 53,
    jobTitle: "Industrial Machinery/Components",
    createdDate: "2/25/2020",
    folder: "Jewelery",
    state: false,
  },
  {
    jobId: 54,
    jobTitle: "Property-Casualty Insurers",
    createdDate: "12/2/2019",
    folder: "Clothing",
    state: true,
  },
  {
    jobId: 55,
    jobTitle: "Real Estate Investment Trusts",
    createdDate: "3/28/2020",
    folder: "Industrial",
    state: true,
  },
  {
    jobId: 56,
    jobTitle: "n/a",
    createdDate: "12/4/2019",
    folder: "Clothing",
    state: true,
  },
  {
    jobId: 57,
    jobTitle: "Major Banks",
    createdDate: "4/27/2020",
    folder: "Tools",
    state: true,
  },
  {
    jobId: 58,
    jobTitle: "Hotels/Resorts",
    createdDate: "3/23/2020",
    folder: "Jewelery",
    state: true,
  },
  {
    jobId: 59,
    jobTitle: "Finance/Investors Services",
    createdDate: "7/9/2020",
    folder: "Health",
    state: false,
  },
  {
    jobId: 60,
    jobTitle: "Banks",
    createdDate: "2/29/2020",
    folder: "Tools",
    state: true,
  },
  {
    jobId: 61,
    jobTitle: "Oil Refining/Marketing",
    createdDate: "12/13/2019",
    folder: "Electronics",
    state: false,
  },
  {
    jobId: 62,
    jobTitle: "Oil Refining/Marketing",
    createdDate: "11/6/2019",
    folder: "Clothing",
    state: false,
  },
  {
    jobId: 63,
    jobTitle: "Real Estate",
    createdDate: "9/12/2019",
    folder: "Electronics",
    state: false,
  },
  {
    jobId: 64,
    jobTitle: "Investment Bankers/Brokers/Service",
    createdDate: "2/17/2020",
    folder: "Home",
    state: true,
  },
  {
    jobId: 65,
    jobTitle: "Precious Metals",
    createdDate: "8/7/2019",
    folder: "Outdoors",
    state: true,
  },
  {
    jobId: 66,
    jobTitle: "n/a",
    createdDate: "1/25/2020",
    folder: "Baby",
    state: false,
  },
  {
    jobId: 67,
    jobTitle: "Environmental Services",
    createdDate: "11/7/2019",
    folder: "Jewelery",
    state: false,
  },
  {
    jobId: 68,
    jobTitle: "n/a",
    createdDate: "7/5/2020",
    folder: "Movies",
    state: false,
  },
  {
    jobId: 69,
    jobTitle: "Clothing/Shoe/Accessory Stores",
    createdDate: "10/26/2019",
    folder: "Electronics",
    state: false,
  },
  {
    jobId: 70,
    jobTitle: "Business Services",
    createdDate: "8/28/2019",
    folder: "Tools",
    state: false,
  },
  {
    jobId: 71,
    jobTitle: "Oil & Gas Production",
    createdDate: "9/4/2019",
    folder: "Jewelery",
    state: false,
  },
  {
    jobId: 72,
    jobTitle: "Industrial Machinery/Components",
    createdDate: "3/3/2020",
    folder: "Sports",
    state: true,
  },
  {
    jobId: 73,
    jobTitle: "Biotechnology: Biological Products (No Diagnostic Substances)",
    createdDate: "3/31/2020",
    folder: "Clothing",
    state: true,
  },
  {
    jobId: 74,
    jobTitle: "Investment Managers",
    createdDate: "6/23/2020",
    folder: "Home",
    state: true,
  },
  {
    jobId: 75,
    jobTitle: "Major Banks",
    createdDate: "3/15/2020",
    folder: "Garden",
    state: false,
  },
  {
    jobId: 76,
    jobTitle: "Real Estate Investment Trusts",
    createdDate: "3/8/2020",
    folder: "Outdoors",
    state: true,
  },
  {
    jobId: 77,
    jobTitle: "Oil & Gas Production",
    createdDate: "8/11/2019",
    folder: "Outdoors",
    state: true,
  },
  {
    jobId: 78,
    jobTitle: "n/a",
    createdDate: "9/24/2019",
    folder: "Jewelery",
    state: false,
  },
  {
    jobId: 79,
    jobTitle: "Food Distributors",
    createdDate: "2/25/2020",
    folder: "Jewelery",
    state: true,
  },
  {
    jobId: 80,
    jobTitle: "Investment Bankers/Brokers/Service",
    createdDate: "10/1/2019",
    folder: "Sports",
    state: false,
  },
  {
    jobId: 81,
    jobTitle: "Natural Gas Distribution",
    createdDate: "8/25/2019",
    folder: "Kids",
    state: false,
  },
  {
    jobId: 82,
    jobTitle: "Packaged Foods",
    createdDate: "11/10/2019",
    folder: "Automotive",
    state: false,
  },
  {
    jobId: 83,
    jobTitle: "Other Consumer Services",
    createdDate: "2/6/2020",
    folder: "Home",
    state: true,
  },
  {
    jobId: 84,
    jobTitle: "Major Banks",
    createdDate: "5/23/2020",
    folder: "Kids",
    state: true,
  },
  {
    jobId: 85,
    jobTitle: "Major Banks",
    createdDate: "12/4/2019",
    folder: "Books",
    state: true,
  },
  {
    jobId: 86,
    jobTitle: "Movies/Entertainment",
    createdDate: "5/31/2020",
    folder: "Games",
    state: true,
  },
  {
    jobId: 87,
    jobTitle: "Packaged Foods",
    createdDate: "10/31/2019",
    folder: "Jewelery",
    state: true,
  },
  {
    jobId: 88,
    jobTitle: "Real Estate Investment Trusts",
    createdDate: "5/22/2020",
    folder: "Health",
    state: true,
  },
  {
    jobId: 89,
    jobTitle: "Major Pharmaceuticals",
    createdDate: "8/31/2019",
    folder: "Kids",
    state: false,
  },
  {
    jobId: 90,
    jobTitle: "Biotechnology: Biological Products (No Diagnostic Substances)",
    createdDate: "7/5/2020",
    folder: "Health",
    state: true,
  },
  {
    jobId: 91,
    jobTitle: "Homebuilding",
    createdDate: "7/25/2020",
    folder: "Grocery",
    state: true,
  },
  {
    jobId: 92,
    jobTitle: "Major Banks",
    createdDate: "5/5/2020",
    folder: "Garden",
    state: false,
  },
  {
    jobId: 93,
    jobTitle: "n/a",
    createdDate: "4/26/2020",
    folder: "Outdoors",
    state: true,
  },
  {
    jobId: 94,
    jobTitle: "Electrical Products",
    createdDate: "12/3/2019",
    folder: "Baby",
    state: false,
  },
  {
    jobId: 95,
    jobTitle: "n/a",
    createdDate: "11/25/2019",
    folder: "Movies",
    state: true,
  },
  {
    jobId: 96,
    jobTitle: "Electrical Products",
    createdDate: "1/29/2020",
    folder: "Clothing",
    state: false,
  },
  {
    jobId: 97,
    jobTitle: "Computer Software: Prepackaged Software",
    createdDate: "6/25/2020",
    folder: "Clothing",
    state: true,
  },
  {
    jobId: 98,
    jobTitle: "Other Specialty Stores",
    createdDate: "7/26/2020",
    folder: "Jewelery",
    state: true,
  },
  {
    jobId: 99,
    jobTitle: "n/a",
    createdDate: "10/9/2019",
    folder: "Movies",
    state: true,
  },
  {
    jobId: 100,
    jobTitle: "Computer Manufacturing",
    createdDate: "8/14/2019",
    folder: "Outdoors",
    state: true,
  },
];

export default mockedJobs;
