const mockedJobs = [
  {
    id: 1,
    title: null,
    createdDate: null,
    folder: "Home",
    state: null,
  },
  {
    id: 2,
    title: "Savings Institutions",
    createdDate: "7/7/2020",
    folder: "Computers",
    state: true,
  },
  {
    id: 3,
    title: null,
    createdDate: null,
    folder: null,
    state: null,
  },
  {
    id: 4,
    title: "n/a",
    createdDate: "9/18/2019",
    folder: "Grocery",
    state: true,
  },
  {
    id: 5,
    title: "Clothing/Shoe/Accessory Stores",
    createdDate: "3/9/2020",
    folder: "Automotive",
    state: true,
  },
  {
    id: 6,
    title: "Major Pharmaceuticals",
    createdDate: "10/26/2019",
    folder: "Computers",
    state: false,
  },
  {
    id: 7,
    title: "Major Pharmaceuticals",
    createdDate: "9/27/2019",
    folder: "Beauty",
    state: true,
  },
  {
    id: 8,
    title: "Industrial Machinery/Components",
    createdDate: "10/20/2019",
    folder: "Grocery",
    state: false,
  },
  {
    id: 9,
    title: "Major Pharmaceuticals",
    createdDate: "6/12/2020",
    folder: "Movies",
    state: false,
  },
  {
    id: 10,
    title: "Major Banks",
    createdDate: "2/25/2020",
    folder: "Grocery",
    state: true,
  },
  {
    id: 11,
    title: "n/a",
    createdDate: "6/22/2020",
    folder: "Shoes",
    state: true,
  },
  {
    id: 12,
    title: "Industrial Specialties",
    createdDate: "6/28/2020",
    folder: "Movies",
    state: false,
  },
  {
    id: 13,
    title: "Electric Utilities: Central",
    createdDate: "12/22/2019",
    folder: "Garden",
    state: true,
  },
  {
    id: 14,
    title: "n/a",
    createdDate: "9/12/2019",
    folder: "Baby",
    state: true,
  },
  {
    id: 15,
    title: "Oil Refining/Marketing",
    createdDate: "11/2/2019",
    folder: "Games",
    state: true,
  },
  {
    id: 16,
    title: "Major Pharmaceuticals",
    createdDate: "10/19/2019",
    folder: "Movies",
    state: true,
  },
  {
    id: 17,
    title: "Major Chemicals",
    createdDate: "4/19/2020",
    folder: "Games",
    state: true,
  },
  {
    id: 18,
    title: "Real Estate Investment Trusts",
    createdDate: "6/1/2020",
    folder: "Baby",
    state: true,
  },
  {
    id: 19,
    title: "Specialty Insurers",
    createdDate: "2/23/2020",
    folder: "Baby",
    state: true,
  },
  {
    id: 20,
    title: "Restaurants",
    createdDate: "8/20/2019",
    folder: "Industrial",
    state: true,
  },
  {
    id: 21,
    title: "Pollution Control Equipment",
    createdDate: "8/4/2020",
    folder: "Outdoors",
    state: true,
  },
  {
    id: 22,
    title: "Business Services",
    createdDate: "10/22/2019",
    folder: "Kids",
    state: true,
  },
  {
    id: 23,
    title: "n/a",
    createdDate: "6/7/2020",
    folder: "Shoes",
    state: true,
  },
  {
    id: 24,
    title: "Industrial Machinery/Components",
    createdDate: "9/9/2019",
    folder: "Jewelery",
    state: true,
  },
  {
    id: 25,
    title: "Major Pharmaceuticals",
    createdDate: "12/2/2019",
    folder: "Books",
    state: true,
  },
  {
    id: 26,
    title: "n/a",
    createdDate: "11/15/2019",
    folder: "Health",
    state: true,
  },
  {
    id: 27,
    title: "Integrated oil Companies",
    createdDate: "12/21/2019",
    folder: "Health",
    state: true,
  },
  {
    id: 28,
    title: "n/a",
    createdDate: "4/8/2020",
    folder: "Grocery",
    state: true,
  },
  {
    id: 29,
    title: "n/a",
    createdDate: "9/13/2019",
    folder: "Baby",
    state: false,
  },
  {
    id: 30,
    title: "Major Pharmaceuticals",
    createdDate: "1/3/2020",
    folder: "Movies",
    state: true,
  },
  {
    id: 31,
    title: "Marine Transportation",
    createdDate: "4/14/2020",
    folder: "Garden",
    state: false,
  },
  {
    id: 32,
    title: "Food Distributors",
    createdDate: "4/20/2020",
    folder: "Outdoors",
    state: false,
  },
  {
    id: 33,
    title: "Business Services",
    createdDate: "6/29/2020",
    folder: "Beauty",
    state: true,
  },
  {
    id: 34,
    title: "Major Banks",
    createdDate: "9/17/2019",
    folder: "Beauty",
    state: false,
  },
  {
    id: 35,
    title: "Industrial Machinery/Components",
    createdDate: "8/12/2019",
    folder: "Shoes",
    state: false,
  },
  {
    id: 36,
    title: "Oil & Gas Production",
    createdDate: "4/19/2020",
    folder: "Shoes",
    state: false,
  },
  {
    id: 37,
    title: "Real Estate Investment Trusts",
    createdDate: "6/29/2020",
    folder: "Tools",
    state: true,
  },
  {
    id: 38,
    title: "Semiconductors",
    createdDate: "5/10/2020",
    folder: "Computers",
    state: false,
  },
  {
    id: 39,
    title: "Property-Casualty Insurers",
    createdDate: "10/13/2019",
    folder: "Industrial",
    state: false,
  },
  {
    id: 40,
    title: "n/a",
    createdDate: "6/29/2020",
    folder: "Tools",
    state: false,
  },
  {
    id: 41,
    title: "Biotechnology: Biological Products (No Diagnostic Substances)",
    createdDate: "11/8/2019",
    folder: "Computers",
    state: true,
  },
  {
    id: 42,
    title: "Paper",
    createdDate: "5/5/2020",
    folder: "Beauty",
    state: true,
  },
  {
    id: 43,
    title: "Business Services",
    createdDate: "3/23/2020",
    folder: "Movies",
    state: false,
  },
  {
    id: 44,
    title: "n/a",
    createdDate: "6/20/2020",
    folder: "Beauty",
    state: false,
  },
  {
    id: 45,
    title: "Real Estate Investment Trusts",
    createdDate: "7/19/2020",
    folder: "Beauty",
    state: true,
  },
  {
    id: 46,
    title: "EDP Services",
    createdDate: "6/12/2020",
    folder: "Grocery",
    state: true,
  },
  {
    id: 47,
    title: "Other Consumer Services",
    createdDate: "2/11/2020",
    folder: "Toys",
    state: false,
  },
  {
    id: 48,
    title: "Marine Transportation",
    createdDate: "12/24/2019",
    folder: "Health",
    state: false,
  },
  {
    id: 49,
    title: "n/a",
    createdDate: "8/1/2020",
    folder: "Home",
    state: false,
  },
  {
    id: 50,
    title: "n/a",
    createdDate: "4/27/2020",
    folder: "Sports",
    state: true,
  },
  {
    id: 51,
    title: "Telecommunications Equipment",
    createdDate: "3/28/2020",
    folder: "Kids",
    state: true,
  },
  {
    id: 52,
    title: "Savings Institutions",
    createdDate: "7/15/2020",
    folder: "Clothing",
    state: true,
  },
  {
    id: 53,
    title: "Industrial Machinery/Components",
    createdDate: "2/25/2020",
    folder: "Jewelery",
    state: false,
  },
  {
    id: 54,
    title: "Property-Casualty Insurers",
    createdDate: "12/2/2019",
    folder: "Clothing",
    state: true,
  },
  {
    id: 55,
    title: "Real Estate Investment Trusts",
    createdDate: "3/28/2020",
    folder: "Industrial",
    state: true,
  },
  {
    id: 56,
    title: "n/a",
    createdDate: "12/4/2019",
    folder: "Clothing",
    state: true,
  },
  {
    id: 57,
    title: "Major Banks",
    createdDate: "4/27/2020",
    folder: "Tools",
    state: true,
  },
  {
    id: 58,
    title: "Hotels/Resorts",
    createdDate: "3/23/2020",
    folder: "Jewelery",
    state: true,
  },
  {
    id: 59,
    title: "Finance/Investors Services",
    createdDate: "7/9/2020",
    folder: "Health",
    state: false,
  },
  {
    id: 60,
    title: "Banks",
    createdDate: "2/29/2020",
    folder: "Tools",
    state: true,
  },
  {
    id: 61,
    title: "Oil Refining/Marketing",
    createdDate: "12/13/2019",
    folder: "Electronics",
    state: false,
  },
  {
    id: 62,
    title: "Oil Refining/Marketing",
    createdDate: "11/6/2019",
    folder: "Clothing",
    state: false,
  },
  {
    id: 63,
    title: "Real Estate",
    createdDate: "9/12/2019",
    folder: "Electronics",
    state: false,
  },
  {
    id: 64,
    title: "Investment Bankers/Brokers/Service",
    createdDate: "2/17/2020",
    folder: "Home",
    state: true,
  },
  {
    id: 65,
    title: "Precious Metals",
    createdDate: "8/7/2019",
    folder: "Outdoors",
    state: true,
  },
  {
    id: 66,
    title: "n/a",
    createdDate: "1/25/2020",
    folder: "Baby",
    state: false,
  },
  {
    id: 67,
    title: "Environmental Services",
    createdDate: "11/7/2019",
    folder: "Jewelery",
    state: false,
  },
  {
    id: 68,
    title: "n/a",
    createdDate: "7/5/2020",
    folder: "Movies",
    state: false,
  },
  {
    id: 69,
    title: "Clothing/Shoe/Accessory Stores",
    createdDate: "10/26/2019",
    folder: "Electronics",
    state: false,
  },
  {
    id: 70,
    title: "Business Services",
    createdDate: "8/28/2019",
    folder: "Tools",
    state: false,
  },
  {
    id: 71,
    title: "Oil & Gas Production",
    createdDate: "9/4/2019",
    folder: "Jewelery",
    state: false,
  },
  {
    id: 72,
    title: "Industrial Machinery/Components",
    createdDate: "3/3/2020",
    folder: "Sports",
    state: true,
  },
  {
    id: 73,
    title: "Biotechnology: Biological Products (No Diagnostic Substances)",
    createdDate: "3/31/2020",
    folder: "Clothing",
    state: true,
  },
  {
    id: 74,
    title: "Investment Managers",
    createdDate: "6/23/2020",
    folder: "Home",
    state: true,
  },
  {
    id: 75,
    title: "Major Banks",
    createdDate: "3/15/2020",
    folder: "Garden",
    state: false,
  },
  {
    id: 76,
    title: "Real Estate Investment Trusts",
    createdDate: "3/8/2020",
    folder: "Outdoors",
    state: true,
  },
  {
    id: 77,
    title: "Oil & Gas Production",
    createdDate: "8/11/2019",
    folder: "Outdoors",
    state: true,
  },
  {
    id: 78,
    title: "n/a",
    createdDate: "9/24/2019",
    folder: "Jewelery",
    state: false,
  },
  {
    id: 79,
    title: "Food Distributors",
    createdDate: "2/25/2020",
    folder: "Jewelery",
    state: true,
  },
  {
    id: 80,
    title: "Investment Bankers/Brokers/Service",
    createdDate: "10/1/2019",
    folder: "Sports",
    state: false,
  },
  {
    id: 81,
    title: "Natural Gas Distribution",
    createdDate: "8/25/2019",
    folder: "Kids",
    state: false,
  },
  {
    id: 82,
    title: "Packaged Foods",
    createdDate: "11/10/2019",
    folder: "Automotive",
    state: false,
  },
  {
    id: 83,
    title: "Other Consumer Services",
    createdDate: "2/6/2020",
    folder: "Home",
    state: true,
  },
  {
    id: 84,
    title: "Major Banks",
    createdDate: "5/23/2020",
    folder: "Kids",
    state: true,
  },
  {
    id: 85,
    title: "Major Banks",
    createdDate: "12/4/2019",
    folder: "Books",
    state: true,
  },
  {
    id: 86,
    title: "Movies/Entertainment",
    createdDate: "5/31/2020",
    folder: "Games",
    state: true,
  },
  {
    id: 87,
    title: "Packaged Foods",
    createdDate: "10/31/2019",
    folder: "Jewelery",
    state: true,
  },
  {
    id: 88,
    title: "Real Estate Investment Trusts",
    createdDate: "5/22/2020",
    folder: "Health",
    state: true,
  },
  {
    id: 89,
    title: "Major Pharmaceuticals",
    createdDate: "8/31/2019",
    folder: "Kids",
    state: false,
  },
  {
    id: 90,
    title: "Biotechnology: Biological Products (No Diagnostic Substances)",
    createdDate: "7/5/2020",
    folder: "Health",
    state: true,
  },
  {
    id: 91,
    title: "Homebuilding",
    createdDate: "7/25/2020",
    folder: "Grocery",
    state: true,
  },
  {
    id: 92,
    title: "Major Banks",
    createdDate: "5/5/2020",
    folder: "Garden",
    state: false,
  },
  {
    id: 93,
    title: "n/a",
    createdDate: "4/26/2020",
    folder: "Outdoors",
    state: true,
  },
  {
    id: 94,
    title: "Electrical Products",
    createdDate: "12/3/2019",
    folder: "Baby",
    state: false,
  },
  {
    id: 95,
    title: "n/a",
    createdDate: "11/25/2019",
    folder: "Movies",
    state: true,
  },
  {
    id: 96,
    title: "Electrical Products",
    createdDate: "1/29/2020",
    folder: "Clothing",
    state: false,
  },
  {
    id: 97,
    title: "Computer Software: Prepackaged Software",
    createdDate: "6/25/2020",
    folder: "Clothing",
    state: true,
  },
  {
    id: 98,
    title: "Other Specialty Stores",
    createdDate: "7/26/2020",
    folder: "Jewelery",
    state: true,
  },
  {
    id: 99,
    title: "n/a",
    createdDate: "10/9/2019",
    folder: "Movies",
    state: true,
  },
  {
    id: 100,
    title: "Computer Manufacturing",
    createdDate: "8/14/2019",
    folder: "Outdoors",
    state: true,
  },
];

export default mockedJobs;
