const mockedPerson = {
  workflows: [
    {
      personId: 0,
      appliedDate: "Aug 9, 2020 2:00:00 AM",
      status: "Start Manual Onboarding",
      jobId: 104,
      jobTitle: "Part Time Marketing Coordinator",
    },
    {
      personId: 1,
      appliedDate: "Aug 9, 2020 2:00:00 AM",
      status: "Interviewed",
      jobId: 104,
      jobTitle: "Part Time Marketing Coordinator",
    },
    {
      personId: 2,
      appliedDate: "Aug 9, 2020 2:00:00 AM",
      status: "Rejected",
      jobId: 104,
      jobTitle: "Part Time Marketing Coordinator",
    },
    {
      personId: 3,
      appliedDate: "Aug 9, 2020 2:00:00 AM",
      status: "Start Manual Onboarding",
      jobId: 109,
      jobTitle: "Full Time Dog Trainer",
    },
    {
      personId: 4,
      appliedDate: "Aug 9, 2020 2:00:00 AM",
      status: "Interviewed",
      jobId: 109,
      jobTitle: "Full Time Dog Trainer",
    },
    {
      personId: 5,
      appliedDate: "Aug 9, 2020 2:00:00 AM",
      status: "Approved",
      jobId: 109,
      jobTitle: "Full Time Dog Trainer",
    },
  ],
  iForms: [
    {
      id: 1234,
      text: null,
      status: null,
      completedDate: null,
      jobId: null,
      jobTitle: null,
    },
    {
      id: 2345,
      text: "Some Test Form Number 2345",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 102,
      jobTitle: "Full Time Tester",
    },
    {
      id: 3456,
      text: "Some Test Form Number 3456",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 103,
      jobTitle: "Full Time Marketing Coordinator",
    },
    {
      id: 4567,
      text: "Some Test Form Number 4567",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 105,
      jobTitle: "Full Time Medical Assistant",
    },
    {
      id: 5678,
      text: "Some Test Form Number 5678",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 107,
      jobTitle: "Full Time Web Designer",
    },
    {
      id: 6789,
      text: "Some Test Form Number 6789",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 109,
      jobTitle: "Full Time Dog Trainer",
    },
    {
      id: 7890,
      text: "Some Test Form Number 7890",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 101,
      jobTitle: "Part Time Tester",
    },
    {
      id: 255341,
      text: "Some Test Form Number 255341",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 103,
      jobTitle: "Full Time Marketing Coordinator",
    },
    {
      id: 111,
      text: "Some Test Form Number 111",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 105,
      jobTitle: "Full Time Medical Assistant",
    },
    {
      id: 222,
      text: "Some Test Form Number 222",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 106,
      jobTitle: "Part Time Medical Assistant",
    },
    {
      id: 333,
      text: "Some Test Form Number 333",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 102,
      jobTitle: "Full Time Tester",
    },
    {
      id: 444,
      text: "Some Test Form Number 444",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 104,
      jobTitle: "Part Time Marketing Coordinator",
    },
    {
      id: 555,
      text: "Some Test Form Number 555",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 109,
      jobTitle: "Full Time Dog Trainer",
    },
    {
      id: 666,
      text: "Some Test Form Number 666",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 111,
      jobTitle: "Full Time President of Sales",
    },
    {
      id: 777,
      text: "Some Test Form Number 777",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 113,
      jobTitle: "Full Time Nursing Assistant",
    },
    {
      id: 888,
      text: "Some Test Form Number 888",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 103,
      jobTitle: "Full Time Marketing Coordinator",
    },
    {
      id: 999,
      text: "Some Test Form Number 999",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 107,
      jobTitle: "Full Time Web Designer",
    },
    {
      id: 901,
      text: "Some Test Form Number 901",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 115,
      jobTitle: "Full Time Project Manager",
    },
    {
      id: 902,
      text: "Some Test Form Number 902",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 112,
      jobTitle: "Part Time President of Sales",
    },
    {
      id: 903,
      text: "Some Test Form Number 903",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 105,
      jobTitle: "Full Time Medical Assistant",
    },
    {
      id: 904,
      text: "Some Test Form Number 904",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 108,
      jobTitle: "Part Time Web Designer",
    },
    {
      id: 905,
      text: "Some Test Form Number 905",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 124,
      jobTitle: "Part Time Quality Control",
    },
    {
      id: 906,
      text: "Some Test Form Number 906",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 111,
      jobTitle: "Full Time President of Sales",
    },
    {
      id: 907,
      text: "Some Test Form Number 907",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 123,
      jobTitle: "Full time Quality Control",
    },
    {
      id: 908,
      text: "Some Test Form Number 908",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 103,
      jobTitle: "Full Time Marketing Coordinator",
    },
    {
      id: 909,
      text: "Some Test Form Number 909",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 107,
      jobTitle: "Full Time Web Designer",
    },
    {
      id: 800,
      text: "Some Test Form Number 800",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 120,
      jobTitle: "Part Time Account Executive",
    },
    {
      id: 801,
      text: "Some Test Form Number 801",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 116,
      jobTitle: "Part Time Project Manager",
    },
    {
      id: 802,
      text: "Some Test Form Number 802",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 104,
      jobTitle: "Part Time Marketing Coordinator",
    },
    {
      id: 803,
      text: "Some Test Form Number 803",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 123,
      jobTitle: "Full time Quality Control",
    },
    {
      id: 804,
      text: "Some Test Form Number 804",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 120,
      jobTitle: "Part Time Account Executive",
    },
    {
      id: 805,
      text: "Some Test Form Number 805",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 101,
      jobTitle: "Part Time Tester",
    },
    {
      id: 806,
      text: "Some Test Form Number 806",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 124,
      jobTitle: "Part Time Quality Control",
    },
    {
      id: 807,
      text: "Some Test Form Number 807",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 106,
      jobTitle: "Part Time Medical Assistant",
    },
    {
      id: 808,
      text: "Some Test Form Number 808",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 124,
      jobTitle: "Part Time Quality Control",
    },
    {
      id: 809,
      text: "Some Test Form Number 809",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 107,
      jobTitle: "Full Time Web Designer",
    },
    {
      id: 700,
      text: "Some Test Form Number 700",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 117,
      jobTitle: "Full Time Librarian",
    },
    {
      id: 701,
      text: "Some Test Form Number 701",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 102,
      jobTitle: "Full Time Tester",
    },
    {
      id: 702,
      text: "Some Test Form Number 702",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 111,
      jobTitle: "Full Time President of Sales",
    },
    {
      id: 703,
      text: "Some Test Form Number 703",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 120,
      jobTitle: "Part Time Account Executive",
    },
    {
      id: 704,
      text: "Some Test Form Number 704",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 106,
      jobTitle: "Part Time Medical Assistant",
    },
    {
      id: 705,
      text: "Some Test Form Number 705",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 122,
      jobTitle: "Part Time Managing Partner",
    },
    {
      id: 706,
      text: "Some Test Form Number 706",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 101,
      jobTitle: "Part Time Tester",
    },
    {
      id: 707,
      text: "Some Test Form Number 707",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 113,
      jobTitle: "Full Time Nursing Assistant",
    },
    {
      id: 708,
      text: "Some Test Form Number 708",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 117,
      jobTitle: "Full Time Librarian",
    },
    {
      id: 709,
      text: "Some Test Form Number 709",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 104,
      jobTitle: "Part Time Marketing Coordinator",
    },
    {
      id: 600,
      text: "Some Test Form Number 600",
      status: "Complete",
      completedDate: "Aug 9, 2020 2:00:00 AM",
      jobId: 106,
      jobTitle: "Part Time Medical Assistant",
    },
  ],
  id: 7800,
  externalId: "099011",
  folder: "Active Folder",
  firstName: "Amparo",
  middleName: "",
  lastName: "Hidalgo",
  email: "something@email.me",
  gender: "Male",
  race: "White (Not Hispanic or Latino)",
  disability: null,
  veteran: null,
  createdDate: "2020-08-09",
  updatedDate: "2020-08-09",
  street: "Some Street 123",
  street2: null,
  zip: "33212",
  city: "Florence",
  country: "United States",
  state: "Arizona",
};

export default mockedPerson;
